fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.22.0"
    mysql:
      repo: "https://github.com/puppetlabs/puppetlabs-mysql.git"
      ref: "3.11.0"
    postgresql:
      repo: "https://github.com/puppetlabs/puppet-postgresql.git"
      ref: "4.9.0"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "1.2.1"
    staging: "https://github.com/nanliu/puppet-staging.git"
    epel:
      repo: "https://github.com/stahnma/puppet-module-epel.git"
      ref: "1.2.2"
    java_ks:
      repo: "https://github.com/puppetlabs/puppetlabs-java_ks.git"
      ref: "1.6.0"
    zypprepo:
      repo: "https://github.com/deadpoint/puppet-zypprepo.git"
      ref: "v1.0.2"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "1.8.0"
    augeasproviders_core: "https://github.com/hercules-team/augeasproviders_core.git"
    augeasproviders_sysctl: "https://github.com/hercules-team/augeasproviders_sysctl.git"
  symlinks:
    cloudera: "#{source_dir}"
